# Generated by Django 2.2.6 on 2021-07-09 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_contact_postform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='PostForm',
        ),
    ]
